### ISSUE TITLE
Core dumps after a while

### ISSUE THREAD

**Issue by oae** [flathub/com.nordpass.NordPass#103]
Nordpass keeps crashing after ~5minutes with the following log. It didn't happen with the snap version. Any idea why?

```sh
20:43:01.967 › internalMessenger:handleMessage: CLOSE_CURRENT_WINDOW
[3:0404/204710.671792:ERROR:browser_main_loop.cc(267)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0404/204710.671864:ERROR:browser_main_loop.cc(267)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0404/204710.671865:ERROR:browser_main_loop.cc(267)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
**
GLib:ERROR:../glib/gvarianttypeinfo.c:186:g_variant_type_info_check: assertion failed: (0 <= index && index < 24)
Bail out! GLib:ERROR:../glib/gvarianttypeinfo.c:186:g_variant_type_info_check: assertion failed: (0 <= index && index < 24)
[0404/204710.672068:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/nordpass: line 2:     3 Aborted                 (core dumped) TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/nordpass/nordpass "$@"

~ took 5m1s 
✖  

```

**Comment by injcristianrojas** [comment]
Same problem here. Using Fedora 37 (GNOME 43.2)

**Comment by rav101** [comment]
I have an issue with core dumps however mine happens at app start up to the point that NordPass is unusable. System details below.

```
ravi@RaviFW13 ~ $ neofetch
            -```````````                  ravi@RaviFW13 
          `-+/------------.`              ------------- 
       .---:mNo---------------.           OS: Solus x86_64 
     .-----yMMMy:---------------.         Host: Laptop 13 (AMD Ryzen 7040Series) A7 
   `------oMMMMMm/----------------`       Kernel: 6.6.8-268.current 
  .------/MMMMMMMN+----------------.      Uptime: 12 mins 
 .------/NMMMMMMMMm-+/--------------.     Packages: 839 (eopkg), 10 (flatpak) 
`------/NMMMMMMMMMN-:mh/-------------`    Shell: bash 5.1.16 
.-----/NMMMMMMMMMMM:-+MMd//oso/:-----.    Resolution: 2256x1504 
-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--    DE: GNOME 45.2 
----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.   WM: Mutter 
.--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`   WM Theme: Everforest-Dark-BL 
`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.    Theme: Everforest-Dark-BL [GTK2/3] 
`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+     Icons: Everforest-Dark [GTK2/3] 
  .------------:://+-/++++++oshddys:      Terminal: gnome-terminal 
   -hhhhyyyyyyyyyyyhhhhddddhysssso-       CPU: AMD Ryzen 7 7840U w/ Radeon 780M Graphics (16) @ 5.132GHz 
    `:ossssssyysssssssssssssssso:`        GPU: AMD ATI c1:00.0 Phoenix1 
      `:+ssssssssssssssssssss+-           Memory: 2857MiB / 59966MiB 
         `-/+ssssssssssso+/-`
              `.-----..`                                          
                                                                  


ravi@RaviFW13 ~ $ flatpak run com.nordpass.NordPass
[3:1229/200000.452493:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 20:00:00.702: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:00:00.703: Failed to load module "canberra-gtk-module"
[3:1229/200000.717817:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1229/200000.717862:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
20:00:00.736 › setAppState: READY
20:00:00.738 › BgAppProcessHandler:start: new bg app started
20:00:00.757 › WebSocket connected to port: 9213
20:00:00.782 › Starting app: Version: 5.11.19; OS: linux x64 6.6.8-268.current; args: 
20:00:00.787 › linux autostart enable: Error: ENOENT: no such file or directory, open 'undefined/meta/gui/nordpass.desktop'
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1133545
    at KE (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1133763)
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2980601
    at Generator.next (<anonymous>)
    at o (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2974758)
20:00:00.792 › BgAppClient:sendMessage: id: 1, APP/LOGIN
[3:1229/200000.795226:ERROR:browser_main_loop.cc(274)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:1229/200000.804994:ERROR:browser_main_loop.cc(274)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:1229/200000.805029:ERROR:browser_main_loop.cc(274)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
20:00:00.807 › keytar:setPassword: Error: The file was externally modified
[3:1229/200000.807775:ERROR:browser_main_loop.cc(274)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[1229/200000.808848:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[64:1229/200001.439195:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -3
/app/bin/nordpass: line 2:     3 Segmentation fault      (core dumped) TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/nordpass/nordpass "$@"
```
