### ISSUE TITLE
linux autostart enable: Error: ENOENT: no such file or directory, open 'undefined/meta/gui/nordpass.desktop'

### ISSUE THREAD

**Issue by darkguy2008** [flathub/com.nordpass.NordPass#116]
I think the last update of today (23 August, 2022) broke the app, I can't start anymore.

Getting this on Fedora 36, GNOME 42:
```
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 19:03:16.417: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:03:16.417: Failed to load module "canberra-gtk-module"
19:03:16.452 › setAppState: READY
19:03:16.455 › BgAppProcessHandler:start: new bg app started
19:03:16.463 › Starting app: Version: 4.29.3; OS: linux x64 5.18.18-200.fc36.x86_64; args: 
19:03:16.466 › WebSocket connected to port: 9213
19:03:16.484 › linux autostart enable: Error: ENOENT: no such file or directory, open 'undefined/meta/gui/nordpass.desktop'
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1948552
    at Dn (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1948770)
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2836332
    at Generator.next (<anonymous>)
    at r (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2832839)
19:03:16.496 › BgAppClient:sendMessage: id: 1, APP/LOGIN
[3:0823/190316.497706:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0823/190316.497755:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0823/190316.500031:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0823/190316.500075:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0823/190316.501639:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0823/190316.501733:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0823/190316.503884:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:0823/190316.503982:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[0823/190316.506358:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0823/190316.506452:ERROR:elf_dynamic_array_reader.h(64)] tag not found
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
/app/bin/nordpass: line 2:     3 Segmentation fault      (core dumped) TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/nordpass/nordpass "$@"
```
Thanks :)

**Comment by FakeShemp** [comment]
I guess they hard-coded the path. AUR is having the same issue. It's probably fixable but I'm not sure how. `undefined` is `${SNAP}`.

**Comment by Fish1** [comment]
Also running into this. Here is my error message.

Sometimes the application actually manages to open to the login screen. But it also happened to crash my computer when I ctrl c terminated it. 

```
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 00:42:06.100: Failed to load module "canberra-gtk-module"
[3:1204/004206.128441:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1204/004206.128469:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
00:42:09.074 › BgAppClient:sendMessage: Error: Bg app was not ready while trying to send ACCOUNT/LIST. Ignoring this message
    at Object.sendMessage (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2875768)
    at cl.sendMessage (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2875182)
    at cl.<anonymous> (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973613)
    at Generator.next (<anonymous>)
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973308
    at new Promise (<anonymous>)
    at ol (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973053)
    at cl.getAccountList (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973559)
    at cl.<anonymous> (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1954548)
    at Generator.next (<anonymous>)
00:42:09.078 › Starting app: Version: 4.33.11; OS: linux x64 6.0.10-1-default; args: 
00:42:09.080 › cl:getAccountList: Error: Something went wrong
    at Object.sendMessage (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2875953)
    at cl.sendMessage (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2875182)
    at cl.<anonymous> (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973613)
    at Generator.next (<anonymous>)
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973308
    at new Promise (<anonymous>)
    at ol (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973053)
    at cl.getAccountList (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1973559)
    at cl.<anonymous> (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1954548)
    at Generator.next (<anonymous>)
00:42:09.082 › WebSocket connected to port: 9213
00:42:09.116 › setAppState: READY
00:42:09.116 › BgAppProcessHandler:start: new bg app started
00:42:09.154 › linux autostart enable: Error: ENOENT: no such file or directory, open 'undefined/meta/gui/nordpass.desktop'
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1926291
    at Vi (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1926509)
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2957868
    at Generator.next (<anonymous>)
    at r (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:2954338)
00:42:09.165 › BgAppClient:sendMessage: id: 1, APP/LOGIN
[3:1204/004209.166762:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:1204/004209.166775:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:1204/004209.177436:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[3:1204/004209.185227:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[1204/004209.201274:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/nordpass: line 2:     3 Segmentation fault      (core dumped) TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/nordpass/nordpass "$@"
```

**Comment by Onirae** [comment]
Hello
I got the same
`$ flatpak run com.nordpass.NordPass 
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 11:53:37.768: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:53:37.769: Failed to load module "appmenu-gtk-module"
[3:0112/115337.861658:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0112/115337.861718:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
11:53:37.930 › setAppState: READY
11:53:37.933 › BgAppProcessHandler:start: new bg app started
11:53:37.950 › Starting app: Version: 4.35.19; OS: linux x64 5.4.225-gentoo-x86_64; args: 
11:53:37.954 › WebSocket connected to port: 9213
11:53:37.974 › linux autostart enable: Error: ENOENT: no such file or directory, open 'undefined/meta/gui/nordpass.desktop'
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:898958
    at Xn (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:899176)
    at /app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1978239
    at Generator.next (<anonymous>)
    at o (/app/extra/nordpass/resources/app.asar/dist/desktop/main/main.js:1:1974741)
11:53:37.989 › BgAppClient:sendMessage: id: 1, APP/LOGIN
[3:0112/115337.991785:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[57:0112/115338.021185:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
11:53:38.291 › BgAppClient:handleMessage: received message with id: 1, APP/LOGIN
11:53:38.292 › BgAppClient:handleNotification: received notification ONLINE/STATUS_CHANGE
11:53:38.292 › handleNotification: online
11:53:38.294 › BgAppMessagesHandler: listening for notifications from the background app ENABLED
[3:0112/115338.311879:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
11:53:38.328 › BgAppClient:handleNotification: received notification ONLINE/STATUS_CHANGE
11:53:38.329 › handleNotification: online
[0112/115338.419583:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/nordpass: line 2:     3 Segmentation fault      TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/nordpass/nordpass "$@"
$`

**Comment by darkguy2008** [comment]
Ah well, guess 2026 won't be the year of the linux desktop either! 🙃

**Comment by yakushabb** [comment]
This app marked as EOL and this repository will be archived soon.

https://github.com/flathub/com.nordpass.NordPass/blob/master/flathub.json
